### ISSUE TITLE
Add an endpoint to monitor e2e access to the BMC

### ISSUE THREAD

**Issue by robertodauria** [m-lab/reboot-service#17] opened 2019-05-21 13:33 UTC
The Reboot API should have an endpoint that attempts to log into a given node using the credentials stored in GCD, runs a no-op command, and verifies end-to-end live access to the BMC is possible.

It should then return a Prometheus metric with the status of this operation, distinguishing among "unable to connect", "unable to log in", "command execution failed", and "ok".

**Comment by nkinkade** [comment] 2019-06-18 23:14
This is a duplicate of https://github.com/m-lab/ops-tracker/issues/401. One of these should be closed... doesn't matter to me which.

**Closed as completed** 2019-08-19 12:36 UTC
Labels: current, 2019, Story, Closed, Week 21, P1, 4
